apiVersion: v1
kind: Service
metadata:
  name: product-bff-service
spec:
  selector:
    app: product-bff-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5003
  type: LoadBalancer
