apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-bff-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-bff-service
  template:
    metadata:
      labels:
        app: user-bff-service
    spec:
      containers:
        - name: user-bff-service-container
          image: gcr.io/micro-services-406818/quickmart-user-bff-service:v2
          ports:
            - containerPort: 5001
          env:
            - name: PORT # Name of the environment variable in your app
              value: '5001'
            - name: SERVICE_NAME
              value: 'user-bff-service'
